nome = str(input('Insira seu nome completo: '))
print('Seu nome em MAIUSCULAS é: ', str.upper(nome))
print('Seu nome em minusculas é: ', str.lower(nome))
print('Nome com iniciais em maíusculo', str.capitalize(nome))
#Para mostrar o número de caracteres menos os espacos encontrados por count(' ')
print('O total de caracteres de seu nome é: ', str(len(nome)-nome.count(' ')))
cada = nome.split()
print('Seu primeiro nome é: {} e seu número de letras é: {}'.format(cada[0], len(cada[0])))
